name: Call Deploy Docs

on:
  push:
    branches:
      - main  # Or adjust as needed for your workflow

jobs:
  call-deploy:
    uses: Telucero/workflows/.github/workflows/deploy-docs.yml@Central_repo_test  
    with:
      branch: main  # Branch to deploy from in the docs repo
      repository: Telucero/tanssi-docs  
      path: tanssi-docs  
      url_prefix: tanssi-mkdocs  
      submodules: true  # Optional, set to false if not using submodules
    secrets: inherit  
#permissions: