name: Trigger Tanssi Docs Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'

jobs:
  deploy-tanssi-docs:
    uses: Telucero/workflows/deploy-docs.yml@Central_repo_test
    with:
      branch: ${{ github.event.inputs.branch || 'main' }}
      repository: Telucero/tanssi-docs
      path: tanssi-docs
      url_prefix: tanssi-mkdocs
      submodules: false  # Set to true if you are using submodules
