name: Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy documentation from"
        required: true
        default: "main"

jobs:
  deploy:
    uses: Telucero/workflows/.github/workflows/deploy-docs.yml@main
    with:
      branch: ${{ inputs.branch }}
      repository: moondance-labs/tanssi-docs
      path: tanssi-docs
      url_prefix: tanssi-mkdocs
